pag_preamble = 18;
pag_introduction = 3;
pag_targets = 5;
pag_stateOfArt = 10;
pag_design = 40;
pag_validation = 10;
pag_results = 5;
pag_conclusions = 3;

pag_total = ...
pag_preamble + ...
pag_introduction + ...
pag_targets + ...
pag_stateOfArt + ...
pag_design + ...
pag_validation + ...
pag_results + ...
pag_conclusions